/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:39:36 GMT 2020
 */

package sg.edu.nus.comp.cs4218.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.exception.FindException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FindException_ESTest extends FindException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FindException findException0 = new FindException((String) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = null;
      FindException findException0 = new FindException((String) null);
      FindException findException1 = new FindException(findException0, string0);
      assertFalse(findException1.equals((Object)findException0));
  }
}
